import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/lib/query";
import { Header } from "@/components/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-secondary text-black">
        <QueryProvider>
          <div className="p-4 max-w-160 w-full mx-auto h-full bg-white flex flex-col gap-4">
            <Header />
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
